[package]
name = "rusty-website"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
chrono = "0.4.45"
liquid = "0.26.11"
liquid-lib = { version = "0.26.11", features = ["jekyll"] }
liquid-core = "0.26.11"
pulldown-cmark = "0.13.4"
serde = "1.0.229"
walkdir = "2.5.0"
yaml_serde = "0.10.7"
